# Generated by Django 5.2.1 on 2025-06-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulo', '0002_remove_appointment_date_remove_appointment_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='package',
        ),
        migrations.AddField(
            model_name='appointment',
            name='package',
            field=models.ManyToManyField(blank=True, null=True, related_name='appointments', to='schedulo.package'),
        ),
    ]
