# Generated by Django 5.2.1 on 2025-06-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulo', '0003_remove_appointment_package_appointment_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.DateTimeField(),
        ),
    ]
