# Generated by Django 5.2.1 on 2025-06-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedulo', '0004_alter_appointment_appointment_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='package',
            new_name='packages',
        ),
    ]
