# Generated by Django 5.2.1 on 2025-12-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedulo", "0005_rename_package_appointment_packages"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
