# Generated by Django 5.2.1 on 2025-12-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedulo", "0006_userprofile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="outlet",
            name="employee_staff",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"user_type": "employee"},
                related_name="outlets",
                to="schedulo.userprofile",
            ),
        ),
    ]
