# Generated by Django 5.2.1 on 2025-12-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedulo", "0007_outlet_employee_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="duration",
            field=models.DurationField(
                blank=True,
                help_text="Total duration of all services in the package",
                null=True,
            ),
        ),
    ]
