# Generated by Django 5.2.1 on 2025-12-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedulo", "0008_package_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
