# Generated by Django 5.2.1 on 2025-12-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedulo", "0009_package_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                    ("cancelled", "Cancelled"),
                    ("confirmed", "Confirmed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
